"""empty message

Revision ID: 275f0cb5ddac
Revises: 900998221a29
Create Date: 2021-10-21 00:58:00.202819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275f0cb5ddac'
down_revision = '900998221a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('gender', sa.String(length=120), nullable=False))
    op.add_column('people', sa.Column('hair_color', sa.String(length=120), nullable=False))
    op.add_column('people', sa.Column('eye_color', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'people', ['eye_color'])
    op.create_unique_constraint(None, 'people', ['hair_color'])
    op.create_unique_constraint(None, 'people', ['gender'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_column('people', 'eye_color')
    op.drop_column('people', 'hair_color')
    op.drop_column('people', 'gender')
    # ### end Alembic commands ###
